#UserArticlesManager/.githab-ci.yml
stages:
  - test

test:
  stage: test
  image: python:3.12
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry --version
    - python --version
    - poetry run mypy . --exclude migrations/env.py
    - poetry run black --check .
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pypoetry
      - poetry.lock

  only:
    - main
