version: '3'
services:
  # Web service for the Flask application
  web:
    build: .  # Build the image from the Dockerfile in the current directory
    ports:
      - "5000:5000"  # Expose port 5000 to the host machine
    depends_on:
      - db  # Ensure the db service is started before the web service
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Use DATABASE_URL environment variable for the database connection
    volumes:
      - .:/app  # Mount the current directory to the /app directory in the container

  # Database service using PostgreSQL
  db:
    image: postgres  # Use the official PostgreSQL image from Docker Hub
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Set the PostgreSQL password from the environment variable
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data in a named volume

# Define named volume for PostgreSQL data storage
volumes:
  postgres_data:
